### ISSUE TITLE
my_all?, my_any?, my_none?

### ISSUE THREAD

**Issue by GabrielJSuarez** [abmAsadullah/Enumerable-Methods-Project#2]
For Patters (Numeric, String, Regexp) use a loop to check if the elements inside the array are equal to that data type, you can use Arr.class and it will return the class of the element, you can also use "#kind_of? Pattern" to make a direct comparison

arr = [1, 2, 3]

[1, 2, 3].my_all?(Numeric)

each_element.class == Numeric

or

each_element.kind_of? Numeric == true

**Comment by guillainbisimwa** [comment]
Thanks
